uninative: Allow multiconfig builds to proceed
Trying to build using multiconfig dependencies shows an error
similar to the following:

bitbake mc::core-image-minimal
ERROR: Unable to start bitbake server (None)
--- Starting bitbake server pid 22806
ERROR: Execution of event handler uninative_event_enable failed

This is very likely caused by bug #13701 on Yocto:
https://bugzilla.yoctoproject.org/show_bug.cgi?id=13071

Since it looks like it tries to execute events for an
incorrect multiconfig.

Add uninative to the distro.conf, to allow multiconfig builds
to proceed properly.

Signed-off-by: Alejandro Hernandez <aehs29@gmail.com>