freertos: handle upstream security flags inclusion
oe-core enabled security flags in 4c2d64c10, this change enabled
-fstack-protector, which when linking against newlib causes errors at link time
since many expected functions are not implemented, such as _kill, _close,
_getpid, _read, _write, _sbrk, etc.

For this test application (freertos-demo), unfortunately we will disable stack
protection to avoid this issue.

We face a similar issue with this commit on stm32, forcing us to disable PIE,
similarly to how we treat it for riscV variants in upstream oe-core, avoiding
text QA errors due to relocations in the .text section:

ERROR: freertos-demo-stm32-FreeRTOSv10.3.1+git-r0 do_package_qa: QA Issue:
freertos-demo-stm32: ELF binary /usr/lib/firmware/FreeeRTOS-STM32-UART.elf has
relocations in .text [textrel]

Signed-off-by: Alejandro Hernandez Samaniego <alejandro@enedino.org>

    oe-core enabled security flags in 4c2d64c10, this change enabled
    -fstack-protector, which when linking against newlib causes errors
    at link time since many expected functions are not implemented, such
    as _kill, _close, _getpid, _read, _write, _sbrk, etc.

    For this test application, unfortunately we will disable stack
    protection to avoid this issue.

Signed-off-by: Alejandro Hernandez Samaniego <alejandro@enedino.org>