freertos-image: fix image name for testing
When inheriting the testimage class, presumably from local.conf,
image-artifact-names takes precedence, causing a naming discrepancy
which eventually produces an error when running the testimage task:

ERROR: File deploy/images/qemuarmv5/freertos-demo-qemuarmv5.testdata.json
Not Found. Have you built the image with INHERIT+="testimage"
in the conf/local.conf?

By overriding IMAGE_BASENAME we can avoid such error, keeping our naming
convention as freertos-image vs freertos-demo ($PN), while being able to
perform automated tests.

Signed-off-by: Alejandro Enedino Hernandez Samaniego <alejandro@enedino.org>